services:
  - type: web
    name: vistagram-backend
    env: python
    plan: free
    buildCommand: chmod +x build_render.sh && ./build_render.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: UPLOAD_DIR
        value: uploads
      - key: REDIS_URL
        value: rediss://red-d28bpi15pdvs738dslmg:Y4rUiJCxdiqNlCWV8Qmzx0faPZDnLxxN@oregon-keyvalue.render.com:6379
      - key: REDIS_DB
        value: 0
      - key: REDIS_PASSWORD
        value: ""
      - key: FRONTEND_URL
        value: "https://vistagram-peach.vercel.app" 